version: "3.8"

services:

  db:
    image: postgres:16.2
#    command: postgres -c 'max_connections=300'
    volumes:
      - ./db-data-app/:/var/lib/postgresql/data/
      - ./shell/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

